apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: namespace-1
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    
