apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: namespace-1
spec:
  selector:
    app: my-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
