apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-mongo
  namespace: namespace-2
spec:
  serviceName: "my-mongo-service"
  replicas: 3
  selector:
    matchLabels:
      app: my-mongo
  template:
    metadata:
      labels:
        app: my-mongo
    spec:
      containers:
      - name: my-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: my-pvc
          mountPath: /data/db
volumeClaimTemplates:
  - metadata:
      name: my-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi